baseURL = "https://mainakdeb.github.io/"
title = "@mainakdeb"
themesDir = "./themes/"
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags/"

[params]
  author = "Mainak Deb"
  description = "Hi, welcome to Mainak's blog"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/Mainakdeb"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/MainakDeb19"


  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
